services:
  db:
    image: postgres:16-alpine
    container_name: url-shortener-db
    environment:
      POSTGRES_DB: urlshortener_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d urlshortener_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: url-shortener-api
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/urlshortener_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: rootpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  postgres_data: