spring:
    application:
        name: url-shortener-api
    datasource:
            url: jdbc:postgresql://localhost:5432/url_shortener
            username: ${DB_USERNAME:postgres}
            password: ${DB_PASSWORD:postgres}
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
logging:
    level:
        com.github.geovanegsfarias: DEBUG