create table urls
(
    id           bigint generated by default as identity
        primary key,
    access_count bigint       not null,
    created_at   timestamp(6) with time zone,
    short_code   varchar(255)
        constraint uko6lree3tj9uru7b4vo07v6s1n
            unique,
    updated_at   timestamp(6) with time zone,
    url          varchar(255) not null
);